### PR TITLE
Remove patches (as they are applied in reverse ..)

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
See https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=248191&view=logs&jobId=656edd35-690f-5c53-9ba3-09c10d0bea97&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d

The patches were fixed upstream and are now incorrectly applied in reverse, undoing the patches ..

**Comment by Tobias-Fischer** [comment]
This is ready to be merged @conda-forge/eigen 

/cc @wolfv

**Comment by jschueller** [comment]
no need to bump

**Comment by jschueller** [comment]
you were right, sorry

**Comment by Tobias-Fischer** [comment]
No worries.

**Pull request closed without merging**
