### PR TITLE
Revert conda-smithy VS9 workaround

### PR DESCRIPTION
**Pull request by patricksnape**
This reverts commit 1b36a6e65f5e85f6546284a5b378ac88066904de, reversing changes made to a14613ccbe60f7c762c4257e2ba601bea6f75bf6.

This should hopefully represent the new build system and the latest conda-build should
sort this out.

### CODE REVIEW

**Comment by jakirkham** [comment]
So, sorry in advance as this isn't obvious, but any branch on a feedstock will deploy anything it builds. This is used for multi-version feedstocks (as we will likely do with OpenCV). However, it isn't used that often and more often people don't like having tons of forked copies of feedstocks or forget/are unaware that this will happen. We are looking positively at proposition which would force branches that deploy to explicitly declare that they do this ( https://github.com/conda-forge/conda-forge.github.io/issues/87 ), but it has not yet been implemented.

**Comment by jakirkham** [comment]
Have absorbed these changes into this PR ( https://github.com/conda-forge/eigen-feedstock/pull/6 ) to get us off the main repo. Thanks @patricksnape.

**Comment by patricksnape** [comment]
@jakirkham OK fair enough.

**Comment by jakirkham** [comment]
Sorry about the confusion. We really should have this stuff documented.

Though if it does pass feel free to merge it. If there is anything I missed, please let me know. Will be out, but should be back Tuesday at the latest.

**Pull request closed without merging**
