### PR TITLE
Revert conda-smithy VS9 workaround (pt. 2)

### PR DESCRIPTION
**Pull request by jakirkham**
Takes these changes ( https://github.com/conda-forge/eigen-feedstock/pull/5 ) and re-renders with conda-smithy 0.9.0 and Travis CI pinning workaround attached to see if that helps. Bumps the build number one more time.

### CODE REVIEW

**Comment by jakirkham** [comment]
BTW if I have not explained this to you yet, @patricksnape. To re-render we just need to install `conda-smithy` from the `conda-forge` channel and run `conda-smithy rerender` in the repo. This will generate all the files needed. Then simply add and commit them. If you need development builds of `conda-smithy`, this is easy to do by building the recipe included in that repo. It keeps tracks of branches in the version name.

**Comment by jakirkham** [comment]
Was missing your `NMake` commit, which I have now merged in here as well.

**Comment by jakirkham** [comment]
Canceled any previous jobs so we can get the results here a little quicker.

**Comment by jakirkham** [comment]
Actually I kind of wonder if this test will actually be useful as we don't set Python during the build. I'm going to fix that.

**Comment by jakirkham** [comment]
Ok, Python is now a Windows build dependency and this has been re-rendered again. This should now be good for testing as the environment is basically the same as it was in staged-recipes.

**Comment by jakirkham** [comment]
Looks like we are good. Thanks for all of your hard work, @patricksnape.

**Comment by patricksnape** [comment]
Why are we fixing the conda-build version? That isn't the latest version! Which sort of negates the point of this haha

**Comment by jakirkham** [comment]
> Why are we fixing the conda-build version? That isn't the latest version! Which sort of negates the point of this haha

That's on Travis CI only. So, no, that is orthogonal to the Windows build fixes.

Unfortunately, I have been out several days and don't recall why it was needed here. Will go back through my notes.

**Comment by jakirkham** [comment]
The pinning on Travis CI was due to this bug ( https://github.com/conda/conda-build/issues/889 ), which doesn't affect Eigen per se, but does affect many Python packages so was added to `conda-smithy` in this PR ( https://github.com/conda-forge/conda-smithy/pull/143 ) and thus shows up in the re-rendering here.

**Pull request merged**
