### PR TITLE
Generate pkg-config files for Windows

### PR DESCRIPTION
**Pull request by seanyen**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This is motivated when I am porting the [`eigenpy`](https://github.com/conda-forge/eigenpy-feedstock) into Windows, where it is using `pkg-config` to discover the dependency.

### CODE REVIEW

**Comment by seanyen** [comment]
cc @jakirkham @patricksnape @jschueller

This is motivated when I am porting the [`eigenpy`](https://github.com/conda-forge/eigenpy-feedstock) into Windows, where it is using `pkg-config` to discover the dependency. Also, in this pull request, I add myself as a co-maintainer.

Please take a look and let me know if anything needs to iterate.

**Comment by jschueller** [comment]
- Where does the eigen.pc patch come from ? upstream ? yourself ?
- For the fortran part, can you explain why eigne fails to disable fortran on its own ?

**Comment by seanyen** [comment]
> * Where does the eigen.pc patch come from ? upstream ? yourself ?

The `eigen.pc.patch` is coming from me. The patch is to make the `eigen.pc` relocatable for `conda` environment. I supposedly should use `has_prefix_files` in the recipe for that. Unfortunately, I never get it worked on Windows. It is most likely due to a [bug](https://github.com/conda/conda-build/issues/3348) for `colcon-build`.

> * For the fortran part, can you explain why eigne fails to disable fortran on its own ?

The errors I saw in Azure DevOps pipelines are as follows:

I haven't deep dive into why the GNU Fortran out-of-box in the VM fails to compile the test program by `CMake`, but the error blocks the `CMake` configuration process.

```
-- The Fortran compiler identification is GNU 8.1.0
-- Check for working Fortran compiler: C:/ProgramData/chocolatey/bin/gfortran.exe
-- Check for working Fortran compiler: C:/ProgramData/chocolatey/bin/gfortran.exe  -- broken
CMake Error at D:/bld/eigen_1570759542605/_build_env/Library/share/cmake-3.15/Modules/CMakeTestFortranCompiler.cmake:45 (message):
  The Fortran compiler

    "C:/ProgramData/chocolatey/bin/gfortran.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: D:/bld/eigen_1570759542605/work/build/CMakeFiles/CMakeTmp
    
    Run Build Command(s):nmake /nologo cmTC_db6ee\fast && 	"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\nmake.exe" -f CMakeFiles\cmTC_db6ee.dir\build.make /nologo -L                  CMakeFiles\cmTC_db6ee.dir\build
    Building Fortran object CMakeFiles/cmTC_db6ee.dir/testFortranCompiler.f.obj
    	C:\ProgramData\chocolatey\bin\gfortran.exe    -c D:\bld\eigen_1570759542605\work\build\CMakeFiles\CMakeTmp\testFortranCompiler.f -o CMakeFiles\cmTC_db6ee.dir\testFortranCompiler.f.obj
    Linking Fortran executable cmTC_db6ee.exe
    	D:\bld\eigen_1570759542605\_build_env\Library\bin\cmake.exe -E remove -f CMakeFiles\cmTC_db6ee.dir/objects.a
    	"" cr CMakeFiles\cmTC_db6ee.dir/objects.a @CMakeFiles\cmTC_db6ee.dir\objects1.rsp
    'cr' is not recognized as an internal or external command,
    operable program or batch file.
    NMAKE : fatal error U1077: '"' : return code '0x1'
    Stop.
    NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\nmake.exe"' : return code '0x2'
    Stop.
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  blas/CMakeLists.txt:9 (enable_language)


-- Configuring incomplete, errors occurred!
```

**Comment by jschueller** [comment]
- Are you sure conda doesnt know how to replace hardcoded paths in text files on its own ?
- It's trying to use mingw, my guess is that it would be enough to pass -DCMAKE_Fortran_COMPILER=0

**Comment by seanyen** [comment]
> * It's trying to use mingw, my guess is that it would be enough to pass -DCMAKE_Fortran_COMPILER=0

`-DCMAKE_Fortran_COMPILER=0` still causes other `CMake` errors down the road. I tried another workaround which is to remove `Chocolatey` `bin` folder from `%PATH%`, so that `GNU Fortron` won't be discoverable by `CMake`. That might be less optimal than using `CMake` flags but should be better than the `patch` way.

**Comment by seanyen** [comment]
> * Are you sure conda doesnt know how to replace hardcoded paths in text files on its own ?

Just want to add more information, `conda` does it automatically, however I believe that functionality doesn't work on Windows. And here is a minimum [change](https://github.com/conda/conda-build/pull/3769) to make it worked on `conda-build`.

**Comment by seanyen** [comment]
@jakirkham @patricksnape @jschueller Sorry to spam you again. Any feedback?

**Comment by seanyen** [comment]
JFYI, https://github.com/conda/conda-build/pull/3769 is merged at the upstream, but it might take time to get it released.

**Comment by brianv0** [comment]
This seems like it could be merged, is there any reason why it isn't?

**Comment by beckermr** [comment]
It appears that a fix was put into conda build that renders one or more of that patches here not needed and we can add stuff to `has_prefix_files`? @seanyen can you comment?

@conda-forge/eigen Can we move this through pls?

**Comment by beckermr** [comment]
@brianv0 you might try adding

```
build:
  has_prefix_files:
    - path/in/output/to/eigen.pc
```

to your PR.

**Comment by seanyen** [comment]
cc @conda-forge/eigen this pull request is ready for review and merge. I removed the `eigen.pc` workaround patch.

@beckermr @brianv0 I checked the devops pipeline is using the latest `conda-build 3.18.11` and I can see the fix now working on `Windows` build. Btw, the `conda-build` exercise all the text files and search for hard-coded path by default, so we don't really need `has_prefix_files` for this case.

**Comment by beckermr** [comment]
Unless you change the provider for windows to azure, this PR cannot yet be merged due to the appveyor failure.

**Comment by seanyen** [comment]
@beckermr I pushed a new change to switch to use Azure. Let's wait and see how the build goes.

**Comment by beckermr** [comment]
It passed!

**Comment by brianv0** [comment]
LGTM?

**Comment by beckermr** [comment]
Most def but we need @conda-forge/eigen to merge

**Comment by beckermr** [comment]
bump on this again @conda-forge/eigen

**Comment by seanyen** [comment]
cc @jakirkham @patricksnape @jschueller please excuse my spam, but it would be great we can move it forward!

**Comment by seanyen** [comment]
@jschueller Thank you!

**Pull request merged**
